name: chronopsi
description: School calendar tool.
autor: Milvintsiss <milvintsiss.com>

publish_to: 'none'

version: 1.4.2+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_boxicons:
    git: https://github.com/Milvintsiss/flutter_boxicons
  eva_icons_flutter: ^2.0.1

  #http requests and parsing
  http: ^0.13.0
  dio: ^4.0.0
  html: ^0.15.0

  #local storage
  shared_preferences: ^2.0.3
  sqflite: ^2.0.0+1
  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.4.0+1
  path_provider: ^2.0.1
  sqlite3_library_windows: ^2.0.1
    #git: https://github.com/Milvintsiss/sqlite3_library_windows
    #path: ../sqlite3_library_windows
  sqlite3_library_linux: ^2.1.0+1
    #git: https://github.com/Milvintsiss/sqlite3_library_linux
    #path: ../sqlite3_library_linux

  #widgets
  table_calendar: ^3.0.0-nullsafety.1
  expansion_tile_card: ^2.0.0
  calendar_strip:
    git: https://github.com/Milvintsiss/flutter_calendar_strip
    #path: ../flutter_calendar_strip
  flutter_duration_picker:
    git: https://github.com/Milvintsiss/flutter_duration_picker
    #path: ../flutter_duration_picker
  number_selection: ^1.0.0

  #locale
  intl: ^0.17.0

  #others
  package_info_plus: ^1.0.0
  url_launcher: ^6.0.2
  external_app_launcher:
    git: https://github.com/Milvintsiss/external_app_launcher
    #path: ../external_app_launcher
  android_intent: ^2.0.0
  adaptive_theme: ^2.0.0-nullsafety.1
  vibration: 1.7.4-nullsafety.0
  diacritic: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

  moor_generator: ^4.1.0
  build_runner: ^1.11.5

  msix: ^0.2.1-nullsafety.0


dependency_overrides:

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/epsiLogo.png
    - assets/appLogo/logo.jpg
    - assets/appLogo/logo.png
    - assets/teamsLogo.png
    - assets/appLogo/logo_avec_padding.png



flutter_icons:
  android: true
  ios: true
  image_path: "assets/appLogo/logo.png"
  image_path_android: "assets/appLogo/logo.png"
  image_path_ios: "assets/appLogo/logo.jpg"


msix_config:
  display_name: Chronopsi
  publisher_display_name: Milvintsiss
  identity_name: 37604Milvintsiss.Chronopsi
  msix_version: 1.4.2.0
  #certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  #certificate_password: 1234 (require if using .pfx certificate)
  publisher: CN=8985C850-4BF3-4FAF-AC5E-FCA703FF0E2A
  logo_path: C:\Users\plest\StudioProjects\Chronopsi\assets\appLogo\logo_avec_padding.png
  start_menu_icon_path: C:\Users\plest\StudioProjects\Chronopsi\assets\appLogo\logo_avec_padding.png
  tile_icon_path: C:\Users\plest\StudioProjects\Chronopsi\assets\appLogo\logo_avec_padding.png
  #vs_generated_images_folder_path: C:\<PathToFolder>\Images
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'