name: chronopsi
version: 1.3.1
summary: Scheduler for EPSI/WIS students
description: Scheduler for EPSI/WIS students

confinement: strict
base: core18
grade: stable

apps:
  chronopsi:
    command: chronopsi
    extensions: [flutter-dev] # Where "master" defines which Flutter channel to use for the build
    plugs:
      - network

parts:
  chronopsi:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
